### PR TITLE
Fixed some responses' content-type  

### PR DESCRIPTION
**Pull request by dang03**

### CODE REVIEW

**Comment by jbonnet** [comment]
@dang03 
Can you confirm? Still getting text:
```
$ curl -v -H 'accept:*/*' -H 'content-type:application/json' s
*   Trying 143.233.127.27...talogues/son-packages/5b926f5d-ecc0-4559-bade-dc3ad3700fb4
* TCP_NODELAY set
* Connected to sp.int3.sonata-nfv.eu (143.233.127.27) port 4002 (#0)
> GET /catalogues/son-packages/5b926f5d-ecc0-4559-bade-dc3ad3700fb4 HTTP/1.1
> Host: sp.int3.sonata-nfv.eu:4002
> User-Agent: curl/7.51.0
> accept:*/*
> content-type:application/json
> 
< HTTP/1.1 200 OK
< Content-Type: text/html;charset=utf-8
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< Content-Length: 7048
< 
PK?vJ??I?<<#service_descriptors/sonata-demo.ymlauthor: Felipe Vicens, Atos IT Solutions and Services Iberia
connection_points:
- id: ns:mgmt
  interface: ipv4
  type: management
- id: ns:input
  interface: ipv4
  type: external
- id: ns:output
  interface: ipv4
  type: external
description: "\"The network service descriptor for the SONATA demo,\n comprising a\
...
```

**Comment by dang03** [comment]
Hi @jbonnet,
Yes, I can confirm it. Please check that your requests are sent to the API v2:
/catalogues/api/v2/son-packages/5b926f5d-ecc0-4559-bade-dc3ad3700fb4

**API v2 is not set to default in the Catalogues yet, so adding **/api/v2/** is required

**Comment by jbonnet** [comment]
Confirmed! ;-)
```
$ curl -v -H 'accept:*/*' -H 'content-type:application/json' sp.int3.sonata-nfv.eu:4002/catalogues/api/v2/son-packages/5b926f5d-ecc0-4559-bade-dc3ad3700fb4
*   Trying 143.233.127.27...
* TCP_NODELAY set
* Connected to sp.int3.sonata-nfv.eu (143.233.127.27) port 4002 (#0)
> GET /catalogues/api/v2/son-packages/5b926f5d-ecc0-4559-bade-dc3ad3700fb4 HTTP/1.1
> Host: sp.int3.sonata-nfv.eu:4002
> User-Agent: curl/7.51.0
> accept:*/*
> content-type:application/json
> 
< HTTP/1.1 200 OK
< Content-type: application/json
< X-Content-Type-Options: nosniff
< Content-Length: 260
< 
* Curl_http_done: called premature == 0
* Connection #0 to host sp.int3.sonata-nfv.eu left intact
{"created_at":"2017-03-27T12:10:03.211+00:00","grid_fs_id":"58d9011b302ec70001000000","grid_fs_name":"\u003cfilename.son\u003e","md5":"ee74a07a023f6b931b4149fba923c404","updated_at":"2017-03-27T12:10:03.211+00:00","uuid":"5b926f5d-ecc0-4559-bade-dc3ad3700fb4"}
```
...but the `filename` is still the generic `"\u003cfilename.son\u003e` (`<filename.son>`)...

**Comment by dang03** [comment]
@jbonnet 
Yes, I see the problem here:
In order to set the filename, the request must include the next header:
`Content-Disposition: attachment; filename=sonata-demo.son`

In the integration test, the curl command does not includes this header, as curl does not allow to modify this header, the `Content-Disposition` within the form part is set to `form-data`

Perhaps, to solve curl POST, Catalogue API will need to be modified in order to accept form-data.
However, with other clients as POSTMAN or HTTP requests, it works properly.

**Comment by jbonnet** [comment]
Hmm...
But integration tests use `curl`, so...

**Comment by dang03** [comment]
@jbonnet,
I have found a curl command that allows setting Content-Disposition field:
`curl -X POST -H "Content-Type: application/zip" -H "Content-Disposition: attachment; filename=sonata-demo_new.son" -H "Cache-Control: no-cache" -H 74d85" "http://sp.int3.sonata-nfv.eu:4002/catalogues/api/v2/son-packages"`

I'm going to update the integration test and see if it works properly.

**Pull request merged**
