### PR TITLE
New features added: API versioning incl v2 and Resources meta-data level

### PR DESCRIPTION
**Pull request by dang03**

### CODE REVIEW

**Comment by dang03** [comment]
Waiting for jenkins to test

**Comment by felipevicens** [comment]
test this please

**Comment by felipevicens** [comment]
test this please

**Comment by felipevicens** [comment]
test this please

**Comment by felipevicens** [comment]
test this please

**Comment by felipevicens** [comment]
test this please

**Comment by felipevicens** [comment]
test this please

**Comment by felipevicens** [comment]
retest this please

**Comment by felipevicens** [comment]
retest this please

**Comment by felipevicens** [comment]
test this please

**Comment by felipevicens** [comment]
test this please

**Comment by felipevicens** [comment]
test this please

**Comment by felipevicens** [comment]
test this please

**Comment by felipevicens** [comment]
test this please

**Pull request merged**
